// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTfoRrIvriqyFV_FNYtxgrrGOeNHoyXdM',
    appId: '1:725677292229:web:7d84eaa990d915c0ad8eac',
    messagingSenderId: '725677292229',
    projectId: 'moviesapp-5434c',
    authDomain: 'moviesapp-5434c.firebaseapp.com',
    storageBucket: 'moviesapp-5434c.firebasestorage.app',
    measurementId: 'G-7VT1M6XDP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVJUAfINB1v5gBGfn-65TizuK6Y2y0Pi4',
    appId: '1:725677292229:android:c28f3d3c820c22a7ad8eac',
    messagingSenderId: '725677292229',
    projectId: 'moviesapp-5434c',
    storageBucket: 'moviesapp-5434c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfeWElgvraD6jy8TkZW7Ea0KZH6_jZOU4',
    appId: '1:725677292229:ios:366d6716126dc220ad8eac',
    messagingSenderId: '725677292229',
    projectId: 'moviesapp-5434c',
    storageBucket: 'moviesapp-5434c.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfeWElgvraD6jy8TkZW7Ea0KZH6_jZOU4',
    appId: '1:725677292229:ios:366d6716126dc220ad8eac',
    messagingSenderId: '725677292229',
    projectId: 'moviesapp-5434c',
    storageBucket: 'moviesapp-5434c.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTfoRrIvriqyFV_FNYtxgrrGOeNHoyXdM',
    appId: '1:725677292229:web:f7180e200a1e1ae7ad8eac',
    messagingSenderId: '725677292229',
    projectId: 'moviesapp-5434c',
    authDomain: 'moviesapp-5434c.firebaseapp.com',
    storageBucket: 'moviesapp-5434c.firebasestorage.app',
    measurementId: 'G-PB47PMGP93',
  );
}
